### ISSUE TITLE
Bug in v1.0.9

### ISSUE THREAD

**Issue by punto338** [Atwa/filepicker#25]
In last version when you try to take a second picture using the camera, this error appears. **In v1.0.8 is working correctly** I guess its because of compileSdk 34

`Writing exception to parcel (Ask Gemini)
                                                                                                    java.lang.SecurityException: Permission Denial: writing androidx.core.content.FileProvider uri content://com.atwa.filepicker.provider/cache/17164781527943286665285211823.jpg from pid=23570, uid=10099 requires the provider be exported, or grantUriPermission()
                                                                                                    	at android.content.ContentProvider.enforceWritePermissionInner(ContentProvider.java:1167)
                                                                                                    	at android.content.ContentProvider.semEnforceWritePermission(ContentProvider.java:1093)
                                                                                                    	at android.content.ContentProvider$Transport.enforceWritePermission(ContentProvider.java:836)
                                                                                                    	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:803)
                                                                                                    	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:609)
                                                                                                    	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:284)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1375)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1311)`

**Comment by Atwa** [comment]
I guess from the stack trace the provider only should be marked as exported.
I'll try to fix this ASAP.
Thanks @punto338

**Comment by punto338** [comment]
> I guess from the stack trace the provider only should be marked as exported. I'll try to fix this ASAP. Thanks @punto338

Also there is an error when trying to install 2 apps both using the file picker. 1st app is installed correctly but when trying to install the second one says:

The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER Installation failed due to: 'Error code: 'INSTALL_FAILED_CONFLICTING_PROVIDER', message='INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name com.atwa.filepicker.provider (in package com.punto338.sample) is already used by com.punto338.othersample'' List of apks: [0] 'app-release.apk'

**Comment by punto338** [comment]
@Atwa any updates about my last message?

**Comment by Atwa** [comment]
@punto338 Closed by https://github.com/Atwa/filepicker/pull/26
